# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/karim/src/iptv_modules

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/karim/src/iptv_modules

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karim/src/iptv_modules/CMakeFiles /home/karim/src/iptv_modules/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/karim/src/iptv_modules/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iptv_in_network

# Build rule for target.
iptv_in_network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iptv_in_network
.PHONY : iptv_in_network

# fast build rule for target.
iptv_in_network/fast:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/build
.PHONY : iptv_in_network/fast

src/iptv_in_network.o: src/iptv_in_network.cpp.o

.PHONY : src/iptv_in_network.o

# target to build an object file
src/iptv_in_network.cpp.o:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/iptv_in_network.cpp.o
.PHONY : src/iptv_in_network.cpp.o

src/iptv_in_network.i: src/iptv_in_network.cpp.i

.PHONY : src/iptv_in_network.i

# target to preprocess a source file
src/iptv_in_network.cpp.i:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/iptv_in_network.cpp.i
.PHONY : src/iptv_in_network.cpp.i

src/iptv_in_network.s: src/iptv_in_network.cpp.s

.PHONY : src/iptv_in_network.s

# target to generate assembly for a file
src/iptv_in_network.cpp.s:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/iptv_in_network.cpp.s
.PHONY : src/iptv_in_network.cpp.s

src/iptv_in_network_gst.o: src/iptv_in_network_gst.cpp.o

.PHONY : src/iptv_in_network_gst.o

# target to build an object file
src/iptv_in_network_gst.cpp.o:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/iptv_in_network_gst.cpp.o
.PHONY : src/iptv_in_network_gst.cpp.o

src/iptv_in_network_gst.i: src/iptv_in_network_gst.cpp.i

.PHONY : src/iptv_in_network_gst.i

# target to preprocess a source file
src/iptv_in_network_gst.cpp.i:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/iptv_in_network_gst.cpp.i
.PHONY : src/iptv_in_network_gst.cpp.i

src/iptv_in_network_gst.s: src/iptv_in_network_gst.cpp.s

.PHONY : src/iptv_in_network_gst.s

# target to generate assembly for a file
src/iptv_in_network_gst.cpp.s:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/iptv_in_network_gst.cpp.s
.PHONY : src/iptv_in_network_gst.cpp.s

src/mongo_driver.o: src/mongo_driver.cpp.o

.PHONY : src/mongo_driver.o

# target to build an object file
src/mongo_driver.cpp.o:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/mongo_driver.cpp.o
.PHONY : src/mongo_driver.cpp.o

src/mongo_driver.i: src/mongo_driver.cpp.i

.PHONY : src/mongo_driver.i

# target to preprocess a source file
src/mongo_driver.cpp.i:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/mongo_driver.cpp.i
.PHONY : src/mongo_driver.cpp.i

src/mongo_driver.s: src/mongo_driver.cpp.s

.PHONY : src/mongo_driver.s

# target to generate assembly for a file
src/mongo_driver.cpp.s:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/mongo_driver.cpp.s
.PHONY : src/mongo_driver.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/iptv_in_network.dir/build.make CMakeFiles/iptv_in_network.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... iptv_in_network"
	@echo "... edit_cache"
	@echo "... src/iptv_in_network.o"
	@echo "... src/iptv_in_network.i"
	@echo "... src/iptv_in_network.s"
	@echo "... src/iptv_in_network_gst.o"
	@echo "... src/iptv_in_network_gst.i"
	@echo "... src/iptv_in_network_gst.s"
	@echo "... src/mongo_driver.o"
	@echo "... src/mongo_driver.i"
	@echo "... src/mongo_driver.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

